
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 15 19:33:11 CST 2026
//----------------------------------------------------

package fes.aragon.sintactico;

import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Fri May 15 19:33:11 CST 2026
  */
public class SintacticoBooleanoCup extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public SintacticoBooleanoCup() {super();}

  /** Constructor which sets the default scanner. */
  public SintacticoBooleanoCup(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SintacticoBooleanoCup(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\013\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\003\004\000\002\003\004\000\002\004\005" +
    "\000\002\004\005\000\002\004\004\000\002\004\003\000" +
    "\002\004\003\000\002\004\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\024\000\014\003\005\007\006\010\012\012\007\013" +
    "\010\001\002\000\016\002\uffff\003\uffff\007\uffff\010\uffff" +
    "\012\uffff\013\uffff\001\002\000\004\004\026\001\002\000" +
    "\012\007\006\010\012\012\007\013\010\001\002\000\012" +
    "\004\ufff9\005\ufff9\006\ufff9\011\ufff9\001\002\000\012\004" +
    "\ufff8\005\ufff8\006\ufff8\011\ufff8\001\002\000\016\002\024" +
    "\003\005\007\006\010\012\012\007\013\010\001\002\000" +
    "\012\007\006\010\012\012\007\013\010\001\002\000\010" +
    "\004\014\005\016\006\015\001\002\000\016\002\ufffe\003" +
    "\ufffe\007\ufffe\010\ufffe\012\ufffe\013\ufffe\001\002\000\012" +
    "\007\006\010\012\012\007\013\010\001\002\000\012\007" +
    "\006\010\012\012\007\013\010\001\002\000\012\004\ufffc" +
    "\005\ufffc\006\015\011\ufffc\001\002\000\012\004\ufffb\005" +
    "\ufffb\006\ufffb\011\ufffb\001\002\000\010\005\016\006\015" +
    "\011\022\001\002\000\012\004\ufff7\005\ufff7\006\ufff7\011" +
    "\ufff7\001\002\000\016\002\001\003\001\007\001\010\001" +
    "\012\001\013\001\001\002\000\004\002\000\001\002\000" +
    "\012\004\ufffa\005\ufffa\006\ufffa\011\ufffa\001\002\000\016" +
    "\002\ufffd\003\ufffd\007\ufffd\010\ufffd\012\ufffd\013\ufffd\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\024\000\010\002\010\003\003\004\012\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\004\024\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\003\022\004" +
    "\012\001\001\000\004\004\020\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\004\017\001\001\000\004\004" +
    "\016\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SintacticoBooleanoCup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SintacticoBooleanoCup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SintacticoBooleanoCup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    // Variable global para guardar el resultado y mandarlo a tu interfaz
    public String resultadoFinal = "";

    @Override
    public void syntax_error(Symbol s) {
        resultadoFinal = "Error sintáctico: No se esperaba el token '" + s.value + "' en la línea " + (s.left + 1) + " columna " + (s.right + 1);
    }

    @Override
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception {
        resultadoFinal = "Error fatal: Expresión incorrecta.";
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$SintacticoBooleanoCup$actions {
  private final SintacticoBooleanoCup parser;

  /** Constructor */
  CUP$SintacticoBooleanoCup$actions(SintacticoBooleanoCup parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$SintacticoBooleanoCup$do_action(
    int                        CUP$SintacticoBooleanoCup$act_num,
    java_cup.runtime.lr_parser CUP$SintacticoBooleanoCup$parser,
    java.util.Stack            CUP$SintacticoBooleanoCup$stack,
    int                        CUP$SintacticoBooleanoCup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SintacticoBooleanoCup$result;

      /* select the action based on the action number */
      switch (CUP$SintacticoBooleanoCup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // expr ::= LPAREN expr RPAREN 
            {
              Boolean RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-1)).right;
		Boolean e = (Boolean)((java_cup.runtime.Symbol) CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-1)).value;
		 RESULT = e; 
              CUP$SintacticoBooleanoCup$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()), RESULT);
            }
          return CUP$SintacticoBooleanoCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // expr ::= FALSE 
            {
              Boolean RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()).right;
		Boolean f = (Boolean)((java_cup.runtime.Symbol) CUP$SintacticoBooleanoCup$stack.peek()).value;
		 RESULT = f; 
              CUP$SintacticoBooleanoCup$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()), RESULT);
            }
          return CUP$SintacticoBooleanoCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // expr ::= TRUE 
            {
              Boolean RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()).right;
		Boolean t = (Boolean)((java_cup.runtime.Symbol) CUP$SintacticoBooleanoCup$stack.peek()).value;
		 RESULT = t; 
              CUP$SintacticoBooleanoCup$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()), RESULT);
            }
          return CUP$SintacticoBooleanoCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // expr ::= NOT expr 
            {
              Boolean RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()).right;
		Boolean e = (Boolean)((java_cup.runtime.Symbol) CUP$SintacticoBooleanoCup$stack.peek()).value;
		 RESULT = !e; 
              CUP$SintacticoBooleanoCup$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()), RESULT);
            }
          return CUP$SintacticoBooleanoCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // expr ::= expr AND expr 
            {
              Boolean RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-2)).right;
		Boolean e1 = (Boolean)((java_cup.runtime.Symbol) CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()).right;
		Boolean e2 = (Boolean)((java_cup.runtime.Symbol) CUP$SintacticoBooleanoCup$stack.peek()).value;
		 RESULT = e1 && e2; 
              CUP$SintacticoBooleanoCup$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()), RESULT);
            }
          return CUP$SintacticoBooleanoCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // expr ::= expr OR expr 
            {
              Boolean RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-2)).right;
		Boolean e1 = (Boolean)((java_cup.runtime.Symbol) CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()).right;
		Boolean e2 = (Boolean)((java_cup.runtime.Symbol) CUP$SintacticoBooleanoCup$stack.peek()).value;
		 RESULT = e1 || e2; 
              CUP$SintacticoBooleanoCup$result = parser.getSymbolFactory().newSymbol("expr",2, ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()), RESULT);
            }
          return CUP$SintacticoBooleanoCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // expr_parte ::= error PUNTOYCOMA 
            {
              Object RESULT =null;
		
                // Permite al compilador recuperarse si hay un error y encuentra un punto y coma
             
              CUP$SintacticoBooleanoCup$result = parser.getSymbolFactory().newSymbol("expr_parte",1, ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()), RESULT);
            }
          return CUP$SintacticoBooleanoCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // expr_parte ::= expr PUNTOYCOMA 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-1)).right;
		Boolean e = (Boolean)((java_cup.runtime.Symbol) CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-1)).value;
		
                parser.resultadoFinal = "Análisis LALR Exitoso. Resultado evaluado: " + e.toString().toUpperCase();
             
              CUP$SintacticoBooleanoCup$result = parser.getSymbolFactory().newSymbol("expr_parte",1, ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()), RESULT);
            }
          return CUP$SintacticoBooleanoCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // expr_lista ::= expr_parte 
            {
              Object RESULT =null;

              CUP$SintacticoBooleanoCup$result = parser.getSymbolFactory().newSymbol("expr_lista",0, ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()), RESULT);
            }
          return CUP$SintacticoBooleanoCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= expr_lista EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-1)).value;
		RESULT = start_val;
              CUP$SintacticoBooleanoCup$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SintacticoBooleanoCup$parser.done_parsing();
          return CUP$SintacticoBooleanoCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // expr_lista ::= expr_lista expr_parte 
            {
              Object RESULT =null;

              CUP$SintacticoBooleanoCup$result = parser.getSymbolFactory().newSymbol("expr_lista",0, ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.elementAt(CUP$SintacticoBooleanoCup$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoBooleanoCup$stack.peek()), RESULT);
            }
          return CUP$SintacticoBooleanoCup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

