
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 15 19:33:10 CST 2026
//----------------------------------------------------

package fes.aragon.sintactico;

/** CUP generated class containing symbol constants. */
public class symBooleanoCup {
  /* terminals */
  public static final int AND = 4;
  public static final int TRUE = 8;
  public static final int EOF = 0;
  public static final int FALSE = 9;
  public static final int error = 1;
  public static final int RPAREN = 7;
  public static final int NOT = 5;
  public static final int PUNTOYCOMA = 2;
  public static final int LPAREN = 6;
  public static final int OR = 3;
}

