
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 26 21:21:07 CST 2026
//----------------------------------------------------

package fes.aragon.sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ABAJO = 6;
  public static final int ARRIBA = 5;
  public static final int INICIO = 2;
  public static final int FIN = 10;
  public static final int EOF = 0;
  public static final int IZQUIERDA = 4;
  public static final int NUMERO = 12;
  public static final int ID = 13;
  public static final int ASIGNACION = 11;
  public static final int error = 1;
  public static final int DERECHA = 3;
  public static final int HASTA = 9;
  public static final int MOVER = 7;
  public static final int REPITE = 8;
}

